---
title: "PDE_CarbonMapperInc"
author: "tyler.richman@erg.com"
date: "1/3/2024"
output: html_document
---
# Plume Data Extraction: Carbon Mapper Inc.

## Execute chunk below to set up work environment
```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

if (!require("sf", character.only = TRUE)) {
  install.packages("sf")
}
if (!require("readxl", character.only = TRUE)) {
  install.packages("readxl")
}
if (!require("writexl", character.only = TRUE)) {
  install.packages("writexl")
}

library("sf")
library("readxl")
library("writexl")

```


## Execute chunk below to initialize parameters
```{r initialize_parameters}
rm(list=ls())

## Input Excel File Path ##
excel_file_path <- "C:/Users/TRichman.ERG/Tyler/Tool Development/Plume Data Extraction/Carbon Mapper Inc/Test Data/TD9_DRAFT_Targeting-NM_WellsForCarbonMapper_2023-11-08.xlsx"

## Output Folder ##
output_folder <- "C:/Users/TRichman.ERG/Tyler/Tool Development/Plume Data Extraction/Carbon Mapper Inc/Output"

## Input Column Names for Coordinates ##
x_field = "LONGITUDE"
y_field ="LATITUDE"

## Input Buffer Distance in Miles ##
bufferDist_mi = 0.5

## Input Plume HTTP GET plume-csv Limit ##
limit = 200

```


## Execute chunk below to obtain plumes
```{r execute}
opt <- options(show.error.messages = TRUE)
on.exit(options(opt))

## URL of Carbon Mapper Plume Data ##
carbonMapperGeoJSON_path = "https://api.carbonmapper.org/api/v1/catalog/sources.geojson"

## Create a Date Frame from Records with non-NA Coordinates in Excel File ##
DF <- read_excel(excel_file_path)
DF[["UID"]] <- seq_len(nrow(DF))
DF <- DF[, c("UID", setdiff(names(DF), "UID"))]

## Remove Facilities from DataFrame that do no have Coordinates ##
if (any(is.na(DF[[x_field]])) | any(is.na(DF[[y_field]]))){
  DF_noCoord <- DF[is.na(DF[[x_field]]) | is.na(DF[[y_field]]),]
  DF <- DF[!(DF[["UID"]] %in% DF_noCoord[["UID"]]),]
}

## Create Spatial Data Frames (SFs) for Facilities and Plumes and Transform to NAD 1983 Equidistant Conic contiguous USA CRS ##
SF_facility <- st_as_sf(
  DF, 
  coords = c(x_field, y_field)
  )
SF_facility <- st_set_crs(SF_facility, 4269) %>% st_transform("ESRI:102005")
SF_plume <- st_read(carbonMapperGeoJSON_path) %>% st_transform("ESRI:102005")

## Create a Buffer with Specified Distance from Facility SF ##
SF_facility_Buffer <- st_buffer(
  SF_facility, 
  dist = units::set_units(bufferDist_mi,"mi")
  )

## Spatial Join Facility Buffer SF with Plume SF ##
SF_joined <- st_join(
  SF_facility_Buffer, 
  SF_plume, 
  join = st_intersects
  )

## Transform SF Joined back into Standard DF ##
DF_joined <-  as.data.frame(SF_joined)
DF_joined <- DF_joined[DF_joined[["plume_ids"]] != "NULL" ,][, c("UID", "plume_ids")]

## Kill program if the number of rows in DF_join is 0 ##
if (nrow(DF_joined) == 0){
  cat(paste("No plume matches made with", excel_file_path))
  opt <- options(show.error.messages = FALSE)
  on.exit(options(opt))
  stop()
}

## Create a New Data Frame to Link Plume ID with Facility ##
DF_link <- data.frame(
  UID = character(),
  plume_id = character()
)

for (i in 1:nrow(DF_joined)){
  DF_temp <- data.frame(
    UID = rep(DF_joined[i, ][["UID"]], times = length(DF_joined[i, ][["plume_ids"]])),
    plume_id = DF_joined[i, ][["plume_ids"]]
  )
  names(DF_temp) <- c("UID", "plume_id")
  
  DF_link <- rbind(DF_link, DF_temp)
}

## Obtain Plume Data from Carbon Mapper ##
base_url = "https://api.carbonmapper.org/api/v1/catalog/plume-csv?plume_names="
end_url = "&sort=desc&limit=500&offset=0"

n = 1

while(n <= length(unique(DF_link[["plume_id"]]))) {
  plume_name_vc <- unique(DF_link[["plume_id"]])[n:(n + limit - 1)]
  plume_name_vc <- plume_name_vc[complete.cases(plume_name_vc)]
  
  plume_names_chr = paste0(plume_name_vc, collapse = "&plume_names=")
  
  url_plumes = paste0(base_url, plume_names_chr, end_url)
  
  if (n == 1){
    DF_plumes <- read.csv(url(url_plumes))
  } else{
    DF_plumes <- rbind(
      DF_plumes,
      read.csv(url(url_plumes))
    )
  }
  n = n + limit
}

## Create Final Data Frame ##
DF_FINAL <- merge(
  DF, 
  DF_link, 
  by = "UID", 
  all.x = TRUE
  )

DF1_len = length(names(DF_FINAL))

DF_FINAL <- DF_FINAL[!is.na(DF_FINAL[["plume_id"]]) ,]

DF_FINAL <- merge(
  DF_FINAL, 
  DF_plumes, 
  by = "plume_id", 
  all.x = TRUE
)

DF_temp <- DF_FINAL[, (DF1_len + 1):length(names(DF_FINAL))] 

DF_FINAL <- cbind(
  DF_FINAL[, 2:DF1_len],
  DF_FINAL[, 1]
)
names(DF_FINAL)[length(names(DF_FINAL))] <- "plume_id"

DF_FINAL <- cbind(
  DF_FINAL[2:length(names(DF_FINAL))],
  DF_temp
)

## Create String Representing the Buffer Distance ##
buffer_str = gsub("\\.", "p", as.character(bufferDist_mi))

## Create String Representing Today's Date ##
today_date <- Sys.Date()
formatted_date <- format(today_date, "%Y%m%d")

## Output Spatial Join and Facilities with Missing Coordinates to Excel ##
out_xlsx_name = paste0(
  gsub(".xlsx", "_CarbonMapperPlumes",basename(excel_file_path)),
  "_",
  buffer_str,
  "mi_",
  formatted_date,
  ".xlsx"
)

write_xlsx(
  DF_FINAL, 
  file.path(output_folder, out_xlsx_name)
)

```
